# run the pipeline on changes in master branch
trigger:
- master

# build environment - OS
pool:
  vmImage: 'ubuntu-latest'
 
steps:

- task: Docker@0
  displayName: 'Run Jekyll'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'jekyll/builder:latest'
    volumes: |
      $(build.sourcesDirectory):/srv/jekyll
      $(build.binariesDirectory):/srv/jekyll/_site
    containerCommand: 'jekyll build --future'
    detached: false
    
- script: |

    # remove git history and settings - to avoid inheritance
    rm -rf .git
    # re-initialise git
    git init
    git config user.name "johnny-renhao"
    git config user.email "2932067657@qq.com"
    git remote add origin https://johnny-renhao:82c4e088a6ca3f7f1ef1d3f61f4352fa11a439ac@github.com/johnny-renhao/www.xierenhao.com.git
    mv _site docs
    git add docs
    git commit -m "deploy the bundle"
    # push the commit to the public repository
    git push origin HEAD:master --force
  displayName: 'deploy the production bundle'