#-------------------------------
# General Site Settings
title: 小谢同学的空间
# logo: logo.svg # You can add own logo.
description: 记录成长路上的点点滴滴


#-------------------------------
# Author Settings
author:
  name: Johnny Xie
  image: 01.jpg
  say-hello: Hello everyone, 我是 <strong>小谢同学</strong>
  bio: 爱说爱笑爱搞怪，喜欢K歌(虽然五音不太全)，爱问为什么，爱学新知识！这是我以前在泰国清迈旅游时喂鸽子的照片，帅吧！


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
# instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
# instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-150968068-2 # Add your identifier. For example UA-99631805-1.

baidu-tongji: any-baidu-id
#-------------------------------
# Newsletter
# mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e